# Generated by Django 4.1.5 on 2023-04-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splatoon_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_id', models.AutoField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=50)),
                ('range_distance', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'weapon',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
