version: '3'

services:
  backend:
    container_name: backend
    build: .
    volumes:
     - ../../backend:/backend
    ports:
     - 8000:8000
    image: spla-app:django
    env_file:
      - ../../.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:15.2
    container_name: db
    volumes:
      - ../../database/:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: ${database}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}