DROP TABLE if exists weapon;
DROP TABLE if exists sub;
DROP TABLE if exists game;
DROP TABLE if exists special;


create table if not exists sub (
    sub_id smallint,
    sub_name varchar(50),
    primary key(sub_id)
);

create table if not exists special (
    special_id smallint,
    special_name varchar(50),
    primary key(special_id)
);

create table if not exists weapon (
    weapon_id smallint,
    weapon_name varchar(50),
    sub_id smallint,
    range_distance smallint,
    types varchar(50),
    primary key(weapon_id),
    foreign key (sub_id) references sub(sub_id)
);

create table if not exists game
(
    season          varchar(50),
    period              timestamp,
    game_ver          varchar(50),
    lobby               varchar(50),
    mode                varchar(50),
    stage               varchar(50),
    time                integer,
    win                 varchar(50),
    knockout            boolean,
    rank                varchar(50),
    power               numeric,
    "alpha-inked"       integer,
    "alpha-ink-percent" numeric,
    "alpha-count"       integer,
    "alpha-color"       varchar(50),
    "alpha-theme"       text,
    "bravo-inked"       integer,
    "bravo-ink-percent" numeric,
    "bravo-count"       integer,
    "bravo-color"       varchar(50),
    "bravo-theme"       varchar(50),
    "A1-weapon"         varchar(50),
    "A1-kill-assist"    integer,
    "A1-kill"           integer,
    "A1-assist"         integer,
    "A1-death"          integer,
    "A1-special"        integer,
    "A1-inked"          integer,
    "A1-abilities"      json,
    "A2-weapon"         varchar(50),
    "A2-kill-assist"    integer,
    "A2-kill"           integer,
    "A2-assist"         integer,
    "A2-death"          integer,
    "A2-special"        integer,
    "A2-inked"          integer,
    "A2-abilities"      json,
    "A3-weapon"         varchar(50),
    "A3-kill-assist"    integer,
    "A3-kill"           integer,
    "A3-assist"         integer,
    "A3-death"          integer,
    "A3-special"        integer,
    "A3-inked"          integer,
    "A3-abilities"      json,
    "A4-weapon"         varchar(50),
    "A4-kill-assist"    integer,
    "A4-kill"           integer,
    "A4-assist"         integer,
    "A4-death"          integer,
    "A4-special"        integer,
    "A4-inked"          integer,
    "A4-abilities"      json,
    "B1-weapon"         varchar(50),
    "B1-kill-assist"    integer,
    "B1-kill"           integer,
    "B1-assist"         integer,
    "B1-death"          integer,
    "B1-special"        integer,
    "B1-inked"          integer,
    "B1-abilities"      json,
    "B2-weapon"         varchar(50),
    "B2-kill-assist"    integer,
    "B2-kill"           integer,
    "B2-assist"         integer,
    "B2-death"          integer,
    "B2-special"        integer,
    "B2-inked"          integer,
    "B2-abilities"      json,
    "B3-weapon"         varchar(50),
    "B3-kill-assist"    integer,
    "B3-kill"           integer,
    "B3-assist"         integer,
    "B3-death"          integer,
    "B3-special"        integer,
    "B3-inked"          integer,
    "B3-abilities"      json,
    "B4-weapon"         varchar(50),
    "B4-kill-assist"    integer,
    "B4-kill"           integer,
    "B4-assist"         integer,
    "B4-death"          integer,
    "B4-special"        integer,
    "B4-inked"          integer,
    "B4-abilities"      varchar(50),
    "medal1-grade"      varchar(50),
    "medal1-name"       varchar(50),
    "medal2-grade"      varchar(50),
    "medal2-name"       varchar(50),
    "medal3-grade"      varchar(50),
    "medal3-name"       varchar(50)
);